In [145]:
import numpy as np

my1dArray = np.array([1,2,3])

my2dArray = np.array([[1,2,3], [4,5,6], [7,8,9]])

# +|-|*|/ is component-wise addition|subtraction|multiplication|division, @ is matrix multiplication
print(my2dArray*my2dArray)
print(my1dArray@my2dArray)
print(my1dArray*my2dArray)
print(my2dArray+my1dArray)
print(my2dArray-my1dArray)
print(my1dArray-my2dArray)
print(my1dArray/my2dArray)
print(my2dArray/my1dArray)

# can do exponential, logarithm, squareroot, sine, cosine
print(np.exp(my1dArray))
print(np.log(my2dArray))
print(np.sqrt(my1dArray))
print(np.sin(my1dArray))
print(np.cos(my1dArray))


[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[30 36 42]
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[0 0 0]
 [3 3 3]
 [6 6 6]]
[[ 0  0  0]
 [-3 -3 -3]
 [-6 -6 -6]]
[[1.         1.         1.        ]
 [0.25       0.4        0.5       ]
 [0.14285714 0.25       0.33333333]]
[[1.  1.  1. ]
 [4.  2.5 2. ]
 [7.  4.  3. ]]
[ 2.71828183  7.3890561  20.08553692]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [129]:
import numpy as np

# creating arrays with float numbers of varying precision
my2dArrayFloat = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype='float')
my2dArrayFloat32 = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=np.float32)

# arrays can have mixed data types, combining into one unicode data type
charArray = np.array([[1,'a', 2], [3, 4, 'zzz']])
print(charArray.dtype)
# datatype will accommodate for the maximum length of character/float 
charArray = np.array([[1,'a', 2], [3, 4, 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz']])
print(charArray.dtype)
# you can assign the data type to create a character limit inside the array
charArray = np.array([[1,'a', 2], [3, 4.2, 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz']], dtype='U10')
print(charArray)

# can create arrays of all one number
array0s = np.zeros((2,3), dtype=int)
print(array0s)
array1s = np.ones((1,5))
print(array1s)
array8s = 8 * np.ones((3,2), dtype=int)
print(array8s)
array10s = np.full((1,4), 10, dtype=int)
print(array10s)
array10s.dtype

<U21
<U66
[['1' 'a' '2']
 ['3' '4.2' 'zzzzzzzzzz']]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1. 1. 1.]]
[[8 8]
 [8 8]
 [8 8]]
[[10 10 10 10]]


dtype('int64')

In [128]:
import numpy as np

# create array of evenly spaced values
start = 10
end = 25
step = 3

evensteps1 = np.arange(start, end)
print(evensteps1)
evensteps = np.arange(start, end, step)
print(evensteps)

# create evenly spaced array between start and end with number of entrys equal to num
linsteps = np.linspace(start, end, num=9)
print(linsteps)

# create identity matrix
identity = np.eye(3)
print(identity)

# create random matrix
random23 = np.random.random((2,3))
print(random23)
randomint23 = np.random.randint(1, 4, (2,3))
print(randomint23)

print(random23.ndim)
print(random23.shape)
print(random23.size)

# diagonal array
b = np.array([[5,6,3],[2,5,1], [4,4,4]])
print(b)
np.diag((b))


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[10 13 16 19 22]
[10.    11.875 13.75  15.625 17.5   19.375 21.25  23.125 25.   ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.2161899  0.403765   0.66649505]
 [0.08053939 0.14676544 0.3614828 ]]
[[2 2 2]
 [2 3 1]]
2
(2, 3)
6
[[5 6 3]
 [2 5 1]
 [4 4 4]]


array([5, 5, 4])

In [126]:
import numpy as np

a = np.array([[2,3,1],[5,0,7]])

# print an element of the array
print(a[1,1])
# print part of a row of the array
print(a[0,1:3])
# print a column of the array
print(a[0:2,1])

# elements of array that are smaller than 3
print(a[a<3])

0
[3 1]
[3 0]
[2 1 0]


In [153]:
import numpy as np

arr = np.array([0,2,4,5,3,7,8,9,5,1])
print(arr)

arr[arr%2==1] = -arr[arr%2==1]
print(arr)

[0 2 4 5 3 7 8 9 5 1]
[ 0  2  4 -5 -3 -7  8 -9 -5 -1]


In [206]:
import numpy as np

# numpy statistics

A = np.random.randint(0, 10, (2,3))
print(A)

# different ways to sum the array
summ1 = A.sum()
summ2 = np.sum(A)
print(summ1)
print(summ2)

# find the maximum of a row or column, or max for each row or column using axis option
maximum = A.max()
print(maximum)
max_row = A[1].max()
max_row = A.max(axis=1)
print(max_row)
max_col = A[0:,1].max()
max_col = A.max(axis=0)
print(max_col)

# can use axis to find the mean of each row/column
mean1 = np.mean(A, axis=0)
mean2 = np.mean(A, axis=1)
print(mean1)
print(mean2)

# same for standard deviation
std1 = np.std(A, axis = 1)
print(std1)

[[5 6 6]
 [7 0 9]]
33
33
9
[6 9]
[7 6 9]
[6.  3.  7.5]
[5.66666667 5.33333333]
[0.47140452 3.8586123 ]


In [271]:
from numpy import linalg as la
import random 

B = np.array([0,0])
C = np.array([0,random.randint(1,10)])
D = np.array([random.randint(1,10),0])

BC = la.norm(B-C)
BD = la.norm(B-D)
CD = la.norm(C-D)

print(BC)
print(BD)
print(CD)
print((BC**2 + BD**2)**(1/2))


4.0
10.0
10.770329614269007
10.770329614269007


In [217]:
import numpy as np

a = np.array([[1,2,5],[7,1,3]])
print(a)

# Transpose, reshape and reshape to row
print(a.T)
print(a.reshape(3,2))
print(a.reshape(6))


[[1 2 5]
 [7 1 3]]
[[1 7]
 [2 1]
 [5 3]]
[[1 2]
 [5 7]
 [1 3]]
[1 2 5 7 1 3]


In [277]:
import numpy as np

# stack arrays by rows and columns, or use concatenate which works in more than 2 dimensions

a = np.array([[1,2,5],[7,1,3]])
b = np.array([[2,5],[7,4]])
c = np.array([[2],[1]])

print(np.hstack([b,a,c]))
print(np.vstack([a.T,b.T,c.T]))
print(np.concatenate((b,a,c), axis=1))
print(np.concatenate((a.T,b.T,c.T), axis=0))


[[2 5 1 2 5 2]
 [7 4 7 1 3 1]]
[[1 7]
 [2 1]
 [5 3]
 [2 7]
 [5 4]
 [2 1]]
[[2 5 1 2 5 2]
 [7 4 7 1 3 1]]
[[1 7]
 [2 1]
 [5 3]
 [2 7]
 [5 4]
 [2 1]]


In [336]:
import numpy as np

# saving arrays to files

a = np.array([[1,2,5],[7,1,2]])
b = np.array([[2,5],[7,4]])

np.save('arrays/array_a', a)
np.savez('arrays/arrays_ab', arr1=a, arr2=b, fmt='%d')
np.savetxt("arrays/array_a.txt", a)
np.savetxt("arrays/array_a2.txt", a, delimiter=',', fmt='%.2f')
np.savetxt("arrays/arrays_a3.csv", a, delimiter=',', fmt='%d')

# loading arrays from files

Anpy = np.load('arrays/array_a.npy')
contents = np.load('arrays/arrays_ab.npz')
Anpz = contents["arr1"]
Bnpz = contents["arr2"]
Atxt = np.loadtxt("arrays/array_a.txt")
Atxt2 = np.loadtxt("arrays/array_a2.txt", delimiter=',')
Acsv = np.loadtxt("arrays/arrays_a3.csv", delimiter=',')

print(Anpy)
print(Anpz)
print(Bnpz)
print(Atxt)
print(Atxt2)
print(Acsv)

[[1 2 5]
 [7 1 2]]
[[1 2 5]
 [7 1 2]]
[[2 5]
 [7 4]]
[[1. 2. 5.]
 [7. 1. 2.]]
[[1. 2. 5.]
 [7. 1. 2.]]
[[1. 2. 5.]
 [7. 1. 2.]]


In [341]:
import numpy as np

data = np.array([[1.99, 2.23],[5.30,7.75],[1.89,3.01]])
rounded_data = np.around(data,1)
str_rounded_data = np.char.mod("%.1f",rounded_data)
str_rounded_data = rounded_data.astype(str)
print(str_rounded_data)

row_header = np.array([['r1'], ['r2'], ['r3']])
row_headed_data = np.hstack((row_header,str_rounded_data))
print(row_headed_data)

column_header = np.array(['c1','c2','c3'])
headed_data = np.vstack((column_header, row_headed_data))
print(headed_data)

      
np.savetxt("arrays/myfile.csv", headed_data, delimiter=',', fmt='%s')

data_loaded = np.loadtxt("arrays/myfile.csv", delimiter=',', dtype=str)
print(data_loaded)

[['2.0' '2.2']
 ['5.3' '7.8']
 ['1.9' '3.0']]
[['r1' '2.0' '2.2']
 ['r2' '5.3' '7.8']
 ['r3' '1.9' '3.0']]
[['c1' 'c2' 'c3']
 ['r1' '2.0' '2.2']
 ['r2' '5.3' '7.8']
 ['r3' '1.9' '3.0']]
[['c1' 'c2' 'c3']
 ['r1' '2.0' '2.2']
 ['r2' '5.3' '7.8']
 ['r3' '1.9' '3.0']]
